const $=s=>document.querySelector(s),screens=[...document.querySelectorAll('section')];let S={stream:null,ctx:null,an:null,rec:null,chunks:[],samples:[],taps:[],blob:null,url:null,metrics:null,result:null,raf:null};
function show(id){screens.forEach(x=>x.classList.remove('active'));$(id).classList.add('active')}const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function stop(){cancelAnimationFrame(S.raf);S.stream?.getTracks().forEach(t=>t.stop());S.ctx?.close();S.stream=S.ctx=S.an=null}
function reset(){S.chunks=[];S.samples=[];S.taps=[];[...$('#taps').children].forEach(x=>x.classList.remove('done'));$('#count').style.display='block';$('#count').textContent='3'}
$('#start').onclick=begin;$('#redo').onclick=begin;$('#cancel').onclick=()=>{stop();show('#home')};$('#next').onclick=()=>show('#home');$('#hist').onclick=()=>{renderHistory();show('#history')};$('#back').onclick=()=>show('#home');$('#analyse').onclick=analyse;$('#save').onclick=save;$('#csv').onclick=exportCSV;$('#clear').onclick=()=>{if(confirm('履歴を削除しますか？')){localStorage.removeItem('kodamaHistory');renderHistory()}};
async function begin(){reset();show('#measure');try{S.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});S.ctx=new(AudioContext||webkitAudioContext)();let src=S.ctx.createMediaStreamSource(S.stream);S.an=S.ctx.createAnalyser();S.an.fftSize=2048;src.connect(S.an);for(let i=3;i;i--){$('#count').textContent=i;await sleep(700)}$('#count').style.display='none';$('#status').textContent='5回ノックしてください';record()}catch(e){alert('マイクを開始できません。HTTPSまたはlocalhostで開き、権限を許可してください。');show('#home')}}
function record(){let mime=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'';S.rec=new MediaRecorder(S.stream,mime?{mimeType:mime}:undefined);S.rec.ondataavailable=e=>e.data.size&&S.chunks.push(e.data);S.rec.onstop=finish;S.rec.start(100);let d=new Float32Array(S.an.fftSize),base=[],last=0,t0=performance.now(),cv=$('#wave'),c=cv.getContext('2d');function loop(){S.an.getFloatTimeDomainData(d);let sum=0;for(let v of d)sum+=v*v;let rms=Math.sqrt(sum/d.length),t=performance.now()-t0;S.samples.push({t,rms});if(t<600)base.push(rms);let noise=base.length?base.reduce((a,b)=>a+b)/base.length:.01,th=Math.max(noise*4.2,.025);if(rms>th&&performance.now()-last>240){last=performance.now();S.taps.push(rms);let i=S.taps.length-1;$('#taps').children[i]?.classList.add('done');navigator.vibrate?.(25);if(S.taps.length>=5)setTimeout(()=>S.rec.state==='recording'&&S.rec.stop(),350)}c.clearRect(0,0,600,180);c.strokeStyle='#63d092';c.beginPath();for(let i=0;i<d.length;i++){let x=i/(d.length-1)*600,y=(.5-d[i]*.44)*180;i?c.lineTo(x,y):c.moveTo(x,y)}c.stroke();if(t>5000&&S.rec.state==='recording')S.rec.stop();else if(S.rec.state==='recording')S.raf=requestAnimationFrame(loop)}loop()}
function quality(){let b=S.samples.filter(x=>x.t<600).map(x=>x.rms),noise=b.length?b.reduce((a,v)=>a+v)/b.length:0,m=S.taps.length?S.taps.reduce((a,v)=>a+v)/S.taps.length:0,sd=S.taps.length?Math.sqrt(S.taps.reduce((a,v)=>a+(v-m)**2,0)/S.taps.length):0,cv=m?sd/m:1;return{noise,cv,noiseLabel:noise<.008?'良好':noise<.02?'許容':'大きい',varLabel:cv<.22?'小さい':cv<.42?'普通':'大きい'}}
function finish(){S.blob=new Blob(S.chunks,{type:S.rec.mimeType||'audio/webm'});S.url&&URL.revokeObjectURL(S.url);S.url=URL.createObjectURL(S.blob);$('#audio').src=S.url;stop();let q=quality();$('#tapQuality').textContent=`${S.taps.length} / 5`;$('#noiseQuality').textContent=q.noiseLabel;$('#varQuality').textContent=q.varLabel;$('#analyse').disabled=S.taps.length<3;show('#review')}
async function analyse(){let a=await S.blob.arrayBuffer(),ctx=new(AudioContext||webkitAudioContext)(),buf=await ctx.decodeAudioData(a.slice(0)),x=buf.getChannelData(0),sr=buf.sampleRate,segs=segments(x,sr),f=segs.map(s=>features(s,sr)).filter(v=>isFinite(v.freq)),avg=k=>f.length?f.reduce((a,v)=>a+v[k],0)/f.length:0,freq=avg('freq'),low=avg('low'),decay=avg('decay'),sd=Math.sqrt(f.reduce((a,v)=>a+(v.freq-freq)**2,0)/(f.length||1)),stability=Math.max(0,1-sd/(freq||1)),q=quality();S.metrics={freq,low,decay,stability,noise:q.noise,tapCount:S.taps.length};S.result=decide(S.metrics);renderResult();ctx.close();show('#result')}
function segments(x,sr){let e=new Float32Array(x.length),w=Math.max(1,Math.floor(sr*.01)),sum=0;for(let i=0;i<x.length;i++){sum+=Math.abs(x[i]);if(i>=w)sum-=Math.abs(x[i-w]);e[i]=sum/Math.min(i+1,w)}let base=[...e.slice(0,Math.min(e.length,Math.floor(sr*.5)))].sort((a,b)=>a-b),th=Math.max((base[Math.floor(base.length/2)]||.001)*7,.012),p=[],last=-sr;for(let i=1;i<e.length-1;i++)if(e[i]>th&&e[i]>=e[i-1]&&e[i]>=e[i+1]&&i-last>sr*.22){p.push(i);last=i}return p.slice(0,5).map(i=>x.slice(Math.max(0,i-sr*.03),Math.min(x.length,i+sr*.42)))}
function features(seg,sr){let n=Math.min(1536,seg.length),step=seg.length/n,out=new Float32Array(n>>1);for(let k=0;k<out.length;k++){let re=0,im=0;for(let i=0;i<n;i++){let v=seg[Math.floor(i*step)]*(.5-.5*Math.cos(2*Math.PI*i/(n-1))),a=2*Math.PI*k*i/n;re+=v*Math.cos(a);im-=v*Math.sin(a)}out[k]=Math.hypot(re,im)}let mi=Math.floor(80*n/sr),ma=Math.min(out.length-1,Math.floor(1200*n/sr)),best=0,bi=mi,lo=0,total=0;for(let i=mi;i<=ma;i++){let e=out[i]**2;total+=e;if(i<=Math.floor(350*n/sr))lo+=e;if(out[i]>best){best=out[i];bi=i}}let peak=0,pi=0;for(let i=0;i<seg.length;i++)if(Math.abs(seg[i])>peak){peak=Math.abs(seg[i]);pi=i}let end=seg.length-1,target=peak*.2;for(let i=pi;i<seg.length;i++)if(Math.abs(seg[i])<target){end=i;break}return{freq:bi*sr/n,low:total?lo/total:0,decay:(end-pi)/sr*1000}}
function decide(m){let s=50,r=[];if(m.freq<300){s+=23;r.push('主共鳴周波数が低く、熟度が進んだ傾向です')}else if(m.freq<430){s+=10;r.push('主共鳴周波数は中間域です')}else{s-=18;r.push('高めの共鳴成分があり、若い可能性があります')}if(m.low>.48){s+=15;r.push('低音成分の割合が高めです')}else if(m.low<.28){s-=10;r.push('低音成分の割合が少なめです')}if(m.decay>150){s+=10;r.push('余韻が比較的長く続いています')}else if(m.decay<75){s-=8;r.push('音の減衰が速めです')}r.push(m.stability>.82?'5回の打音が安定しています':'打音のばらつきがあり、確からしさを下げています');let label=s<43?'まだ早い':s>78?'遅めの可能性':'収穫適期候補',q=Math.min(1,m.tapCount/5)*.35+Math.min(1,m.stability)*.35+Math.max(0,1-m.noise/.03)*.3;return{label,score:Math.max(0,Math.min(100,Math.round(s))),confidence:Math.round(45+q*45),reasons:r}}
function renderResult(){let r=S.result,m=S.metrics;$('#label').textContent=r.label;$('#score').textContent=r.score;$('#confidence').textContent=r.confidence+'%';$('#reasons').innerHTML=r.reasons.map(x=>`<li>${x}</li>`).join('');$('#freq').textContent=Math.round(m.freq)+' Hz';$('#low').textContent=m.low.toFixed(2);$('#decay').textContent=Math.round(m.decay)+' ms';$('#stability').textContent=Math.round(m.stability*100)+'%'}
function history(){try{return JSON.parse(localStorage.getItem('kodamaHistory')||'[]')}catch{return[]}}function save(){let h=history();h.unshift({id:$('#fruit').value||new Date().toISOString(),variety:$('#variety').value||'小玉スイカ',pollination:$('#pollination').value,at:new Date().toISOString(),result:S.result,metrics:S.metrics,feedback:''});localStorage.setItem('kodamaHistory',JSON.stringify(h));alert('保存しました');show('#home')}
function renderHistory(){let h=history(),list=$('#list');list.innerHTML=h.length?'':'履歴はまだありません。';h.forEach((x,i)=>{let d=document.createElement('div');d.className='item';d.innerHTML=`<div class="itemtop"><strong>${x.id} / ${x.variety}</strong><span class="badge">${x.result.label} ${x.result.score}点</span></div><small>${new Date(x.at).toLocaleString('ja-JP')}・受粉日 ${x.pollination||'未入力'}・${Math.round(x.metrics.freq)}Hz</small><div class="feedback">収穫後：${['早い','ぴったり','遅い'].map(v=>`<button data-v="${v}" class="${x.feedback===v?'selected':''}">${v}</button>`).join('')}</div>`;d.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{let a=history();a[i].feedback=b.dataset.v;localStorage.setItem('kodamaHistory',JSON.stringify(a));renderHistory()});list.appendChild(d)})}
function exportCSV(){let h=history();if(!h.length)return alert('履歴がありません');let rows=[['個体ID','品種','受粉日','測定日時','判定','点数','確からしさ','周波数Hz','低域比率','減衰ms','安定度','打音数','収穫後評価'],...h.map(x=>[x.id,x.variety,x.pollination,x.at,x.result.label,x.result.score,x.result.confidence,Math.round(x.metrics.freq),x.metrics.low.toFixed(3),Math.round(x.metrics.decay),x.metrics.stability.toFixed(3),x.metrics.tapCount,x.feedback])],csv='\uFEFF'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='kodama_sound.csv';a.click()}if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
